/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as ChangelogRouteRouteImport } from './routes/changelog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as DocsIdRouteImport } from './routes/docs/$id'
import { Route as ChangelogVersionRouteImport } from './routes/changelog/$version'

const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRouteRoute = ChangelogRouteRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChangelogRouteRoute,
} as any)
const DocsIdRoute = DocsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocsRouteRoute,
} as any)
const ChangelogVersionRoute = ChangelogVersionRouteImport.update({
  id: '/$version',
  path: '/$version',
  getParentRoute: () => ChangelogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/changelog/$version': typeof ChangelogVersionRoute
  '/docs/$id': typeof DocsIdRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog/$version': typeof ChangelogVersionRoute
  '/docs/$id': typeof DocsIdRoute
  '/changelog': typeof ChangelogIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/changelog/$version': typeof ChangelogVersionRoute
  '/docs/$id': typeof DocsIdRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/docs'
    | '/changelog/$version'
    | '/docs/$id'
    | '/changelog/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/changelog/$version' | '/docs/$id' | '/changelog' | '/docs'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/docs'
    | '/changelog/$version'
    | '/docs/$id'
    | '/changelog/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRouteRoute: typeof ChangelogRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof ChangelogRouteRoute
    }
    '/docs/$id': {
      id: '/docs/$id'
      path: '/$id'
      fullPath: '/docs/$id'
      preLoaderRoute: typeof DocsIdRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/changelog/$version': {
      id: '/changelog/$version'
      path: '/$version'
      fullPath: '/changelog/$version'
      preLoaderRoute: typeof ChangelogVersionRouteImport
      parentRoute: typeof ChangelogRouteRoute
    }
  }
}

interface ChangelogRouteRouteChildren {
  ChangelogVersionRoute: typeof ChangelogVersionRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
}

const ChangelogRouteRouteChildren: ChangelogRouteRouteChildren = {
  ChangelogVersionRoute: ChangelogVersionRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
}

const ChangelogRouteRouteWithChildren = ChangelogRouteRoute._addFileChildren(
  ChangelogRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsIdRoute: typeof DocsIdRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsIdRoute: DocsIdRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRouteRoute: ChangelogRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
